### ISSUE TITLE
Failed to build with external abseil-cpp

### ISSUE THREAD

**Issue by hcoona** [open-telemetry/opentelemetry-cpp#1065] opened 2021-11-15 05:56 UTC
It's simple to understand so I didn't follow the template.

The opentelemetry-cpp vendor parts of the absl source code within the API but without change the namespace. If I build a cpp target included both opentelementry-cpp & abseil-cpp, it would occurred an error (build with bazel & llvm-13):

```text
external/com_google_absl/absl/meta/type_traits.h:162:8: error: redefinition of 'is_detected_convertible_impl<typename std::enable_if<std::is_convertible<Op<Args...>, To>::value>::type, To, Op, Args...>'
struct is_detected_convertible_impl<
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
bazel-out/k8-fastbuild/bin/external/io_opentelemetry_cpp/api/_virtual_includes/api/opentelemetry/nostd/./absl/types/../types/internal/../../meta/type_traits.h:154:8: note: previous definition is here
struct is_detected_convertible_impl<
       ^
```

The critical rule is to use an alternative namespace than the original namespace `absl` when vendoring any source code.

**Comment by hcoona** [comment] 2021-11-15 06:04
Still failing after add `--copt -DHAVE_ABSEIL=1` to `.bazelrc`

**Comment by lalitb** [comment] 2021-11-15 06:11
Does change the order of inclusion of header file helps as documented here: https://github.com/open-telemetry/opentelemetry-cpp/blob/main/examples/otlp/README.md#additional-notes-regarding-abseil-library

If not, please let us know the version of abseil-cpp used externally?

**Comment by hcoona** [comment] 2021-11-16 04:00
I didn't try changing the order. It's ridiculous to make it work relying about including order, and our coding guideline disallow manually ordering the includes.

The abseil-cpp commit id is 3c8b5d7 from master branch.

**Comment by lalitb** [comment] 2021-11-16 04:07
Agree, I still believe -DHAVE_ABSEIL=ON should work in this case. If not, this needs to be fixed.

**Comment by lalitb** [comment] 2021-12-01 22:41
Tested with below cmake command, and the build and tests were successful:
```
$ cmake -DWITH_ABSEIL=ON -DCMAKE_PREFIX_PATH=/home/labhas/custom_abseil/ .. && make -j14
```

Looks like the problem is specific to bazel. Need to test more.

**Comment by owent** [comment] 2021-12-28 06:53
We meet the same problem and I solve this problem by add modify `HAVE_ABSEIL` to [api/BUILD](api/BUILD) and the move the paths of internal abseil-cpp.
This issue can assign to me and I can try to merge the changes here and add some tests some days later. @lalitb

**Comment by lalitb** [comment] 2021-12-28 07:30
Thanks, @owent. Assigned to you.

**Closed** 2022-01-15 00:53 UTC
Labels: bug
