### ISSUE TITLE
Using `libcurl-multi` to implement `opentelemetry::ext::http::client::curl::HttpClient`

### ISSUE THREAD

**Issue by owent** [open-telemetry/opentelemetry-cpp#1243] opened 2022-03-04 03:17 UTC
**Is your feature request related to a problem?**

To improve IO performance as mentioned in #1175 and #1176 

**Describe the solution you'd like**

Using  `libcurl-multi` instead of invoking threads for `HttpClient`.

**Additional context**

+ https://curl.se/libcurl/c/libcurl-multi.html
+ https://curl.se/libcurl/c/multi-double.html

**Comment by owent** [comment] 2022-03-04 03:19
This issue can be assigned to me, and I will finish it several days later.There will not be any conflict with #1209 .

**Comment by lalitb** [comment] 2022-03-04 03:41
Thanks. Was thinking to create an issue for this.

**Comment by ThomsonTan** [comment] 2022-03-04 17:15
Do we need provide an option for libcurl vs. libcurl-multi? I think libcurl-multi could take more resource usage, so may be not expected for some scenario?

**Comment by owent** [comment] 2022-03-04 17:44
> Do we need provide an option for libcurl vs. libcurl-multi? I think libcurl-multi could take more resource usage, so may be not expected for some scenario?

I think we can use libcurl-multi in SendAsync and still use libcuel-easy in Send.
To my understanding, libcurl-multi do not cost more because we use `select()` to wait for response , when we use libcurl-multi, we just use `curl_multi_poll()` to replace `select()`.

**Comment by owent** [comment] 2022-04-03 16:45
Can I do some break changes to `curl::HttpOperator` to finish this feature? `multi_handle` will be shared between visisted by more than one thread, I have to change  the way to share data to keep thread-safety and I think `curl::HttpOperator` is not for SDK's user.

**Comment by meastp** [comment] 2022-04-28 12:08
Hi - I'm using the otlp http exporter, and I'm hitting the issue described in [this thread](https://curl-library.cool.haxx.narkive.com/kRBuxBFC/couldn-t-connect-error-address-already-in-use) and updating the registry key resolves the issue. However, as mentioned in the thread, the way `curl_easy_init()` and `curl_easy_cleanup()` is used isn't good. What I'm wondering is if this issue is also resolved when moving to `libcurl-multi`?

**Comment by lalitb** [comment] 2022-04-28 12:31
> I think the issue is that a new session (with calling both curl_easy_init() and curl_easy_cleanup() every time) is used every time Export is called

Is the issue due to local port reuse/overlap? In current setup, the sessions are not concurrent, so the problem should only happen if cleanup is not happening properly in some scenario.

**Comment by meastp** [comment] 2022-04-28 13:25
@lalitb Yes, I believe that's the cause, but I'm not sure about the specifics. It might be Windows specific, but please reuse the CURL* resource if possible, to avoid this problem.

The problem disappeared in my tests (no output to stdout/stderr from otel-cpp/curl) after creating the registry key as specified in the linked thread above. I modified to `curl_easy_setopt(curl_, CURLOPT_VERBOSE, 1L);` to debug/read output from Curl, because the output from otel-cpp was rather sparse.

**Comment by meastp** [comment] 2022-04-29 10:58
> (...) it also allow us to reuse connections for a lot of `curl_easy_handle`.

@owent This is the crucial bit that will solve the problem, I think. Thanks :)

**Closed** 2022-07-09 07:17 UTC
