### ISSUE TITLE
Scope should be default constructable 

### ISSUE THREAD

**Issue by VivekSubr** [open-telemetry/opentelemetry-cpp#1889] opened 2022-12-27 11:43 UTC
**Is your feature request related to a problem?**
Wrapping a span in a class so that'll be a global object necessitates keeping track of scopes as members... but making a scope as a member variable is difficult as it is not default constructible.

**Describe the solution you'd like**
Make Scope default constructible, ie add 'Scope() = default' to the class.

**Comment by lalitb** [comment] 2022-12-27 11:59
`Scope` need to be associated with a `Span` during it's construction.  It doesn't make sense to have the default constructor for it. Can you share with an example what you are trying to achieve?

**Comment by sirzooro** [comment] 2022-12-27 16:55
I logged similar issue in the past, with possible workaround: https://github.com/open-telemetry/opentelemetry-cpp/issues/1298

**Comment by VivekSubr** [comment] 2022-12-28 05:55
@sirzooro - thank you, I just added the default constructor and recompiled.

@lalitb - Let's say we are wrapping an global 'active span' for a application within a class, and provide a startSpan api, which sets the ActiveSpan in trace::tracer as well,
```
 m_currentSpan  = m_tracer->StartSpan(spanName);
 m_tracer->WithActiveSpan(m_currentSpan);
```

We need to keep track of the scopes as well, but scope can't be made a member variable since it's not default constructible.

**Comment by sirzooro** [comment] 2023-01-08 08:44
> @sirzooro - thank you, I just added the default constructor and recompiled.

I mentioned different solution in that issue - use unique_ptr to store Scope object. Here is code snipped copied from that issue:
```cpp
std::unique_ptr<opentelemetry::trace::Scope> scope;
if (...)
    scope = std::unique_ptr<opentelemetry::trace::Scope>(new opentelemetry::trace::Scope(tracer->WithActiveSpan(span)));
```

**Comment by VivekSubr** [comment] 2023-01-09 05:10
@sirzooro - that doesn't help... still get the destructor crash as above.

**Comment by sirzooro** [comment] 2023-01-09 11:04
@VivekSubr maybe that default constructor which you added breaks something? I use Scope move constructor when I put it into unique_ptr like in code above, and this works fine for me.

**Comment by VivekSubr** [comment] 2023-01-09 11:32
@sirzooro - Crash happened without the default constructor... I have a deque<Scope> as a member variable of a wrapper class, and it crashes with the above trace on destruction of the wrapper class. 

Commenting out the 'Detach' in Token destructor makes this crash go away.

**Comment by VivekSubr** [comment] 2023-01-10 14:05
@lalitb / @sirzooro  - additional info, it only happens if the wrapper class is static (in my case, singleton).

So, default contructed scope (either by adding the constructor or by sirzooro's move constructor way), and the context being static triggers this crash.

**Comment by lalitb** [comment] 2023-02-02 18:32
@VivekSubr - Sorry, I haven't been following up with this issue. Is this issue still relevant ?

**Comment by lalitb** [comment] 2023-02-18 00:31
Closing. please reopen if the issue is still relevant.

**Closed by lalitb** 2023-02-18 00:31 UTC
