### ISSUE TITLE
Provide a way to disable collection

### ISSUE THREAD

**Issue by Falmarri** [open-telemetry/opentelemetry-cpp#2262] opened 2023-08-12 19:57 UTC
There's no simple way to disable the collection of traces, since the setup has to be done manually. What I was thinking was that instead of providing a default trace API url of `"http://localhost:4318/v1/traces"`, if you have not set up an endpoint it should just disable sending traces and default to the no-op tracer.

OR, if it can be exposed that it's taking up the default, it can be manually disabled. But as of now, there's no easy way to check if it's just using the defaults or if it was explicitly set, without manually checking the env variables again. And since the env variables and default value are declared as constexpr inside the scope of the GetDefault function, it has to be re-implemented

**Comment by esigo** [comment] 2023-08-14 20:21
related #1631

**Comment by marcalff** [comment] 2023-09-01 15:27
Closing as a duplicate of #1631 (which is not yet implemented in opentelemetry-cpp)

**Closed** 2023-09-01 15:28 UTC
Labels: triage/duplicate
