### ISSUE TITLE
Regex crash in TraceState::IsValidKeyRegEx on Debian

### ISSUE THREAD

**Issue by matt-goldsmith-okcupid** [open-telemetry/opentelemetry-cpp#1126] opened 2021-12-09 23:43 UTC
**Describe your environment**

Dockerized Debian 9 (Stretch). Built with `clang++-6.0`.

**Steps to reproduce**

Run `TraceState::FromHeader`.

**What is the expected behavior?**

Get a `TraceState` object.

**What is the actual behavior?**

Crash with:

`std::__throw_regex_error (__ecode=std::regex_constants::_S_error_range, __what=0x7fa18e4b973b "Invalid range in bracket expression.")`

**Additional context**

See [this StackOverflow post](https://unix.stackexchange.com/questions/562590/bad-regex-invalid-range-end/562592#562592). Replacing the two regexes in `TraceState::IsValidKeyRegEx` with these two fixes the problem (note the `-` characters):

```cpp
static std::regex reg_key("^[a-z0-9][a-z0-9*_/-]{0,255}$");
static std::regex reg_key_multitenant(
   "^[a-z0-9][a-z0-9*_/-]{0,240}(@)[a-z0-9][a-z0-9*_/-]{0,13}$");
```

**Comment by lalitb** [comment] 2021-12-10 18:42
Can you provide a small working example for this, as I can't reproduce it using clang6/gcc.

**Comment by matt-goldsmith-okcupid** [comment] 2021-12-10 19:18
Hi lalitb! [Here's a gist](https://gist.github.com/matt-goldsmith-okcupid/863fc0b2e48d7486efe55c4a33b5fed3).

**Comment by lalitb** [comment] 2021-12-10 21:02
Thanks. strange, but I don't see any crash/exception while running above code snippet on clang-6 here : https://godbolt.org/z/MjWrPdMzf

**Comment by lalitb** [comment] 2022-01-07 18:49
Closing as this is not reproducible. Feel free to reopen this, and contribute a fix, if this is a valid issue.

**Closed by lalitb** 2022-01-07 18:49 UTC
Labels: bug
