### ISSUE TITLE
link OPENTELEMETRY_CPP_LIBRARIES error

### ISSUE THREAD

**Issue by wy12148** [open-telemetry/opentelemetry-cpp#2286] opened 2023-09-01 08:43 UTC
The centos8 system is constructed using cmake on the Intranet. The opentelemetry system is constructed using cmake

cmake .. -DWITH_OTLP_GRPC=ON -DWITH_OTLP_HTTP=ON -DBUILD_TESTING=OFF -DWITH_EXAMPLES=OFF -DWITH_JAEGER=ON -DOTELCPP_PROTO_PATH=/opt/programs/opentelemetry-proto -DCMAKE_CXX_STANDRAT=14 -DWITH_STL=ON
-- Building for architecture ARCH=x64
-- PROTOBUF_PROTOC_EXECUTABLE=/usr/local/bin/protoc
-- opentelemetry-proto dependency satisfied by: external path
-- gRPC_CPP_PLUGIN_EXECUTABLE=/usr/local/bin/grpc_cpp_plugin
-- Found CURL: /usr/lib64/libcurl.so, version 
-- nlohmann::json dependency satisfied by: package
Building with standard library types...
-- Configuring done
-- Generating done
-- Build files have been written to: /opt/programs/opentelemetry-cpp/build

and the make command is executed successfully

When I build a demo with cmake，it‘s ok. But there are many errors when executing the make command, such as

/usr/local/include/opentelemetry/trace/span_context_kv_iterable_view.h:111:80: error: 'AttributeValue' is not a member of 'opentelemetry::v1::common'; did you mean 'AttributeType'?
  111 |                        nostd::span<const std::pair<nostd::string_view, common::AttributeValue>>{
      |                                                                                ^~~~~~~~~~~~~~
      |                                                                                AttributeType
/usr/local/include/opentelemetry/trace/span_context_kv_iterable_view.h:111:80: error: 'AttributeValue' is not a member of 'opentelemetry::v1::common'; did you mean 'AttributeType'?
  111 |                        nostd::span<const std::pair<nostd::string_view, common::AttributeValue>>{
      |                                                                                ^~~~~~~~~~~~~~
      |                                                                                AttributeType
/usr/local/include/opentelemetry/trace/span_context_kv_iterable_view.h:111:80: error: template argument 1 is invalid
/usr/local/include/opentelemetry/trace/span_context_kv_iterable_view.h:111:80: error: template argument 2 is invalid
/usr/local/include/opentelemetry/trace/span_context_kv_iterable_view.h:111:94: error: template argument 1 is invalid
  111 |                        nostd::span<const std::pair<nostd::string_view, common::AttributeValue>>{
      |                                                                                              ^~
/usr/local/include/opentelemetry/trace/span_context_kv_iterable_view.h:112:39: error: request for member 'begin' in 'attributes', which is of non-class type 'int'
  112 |                            attributes.begin(), attributes.end()},
      |                                       ^~~~~
/usr/local/include/opentelemetry/trace/span_context_kv_iterable_view.h:112:59: error: request for member 'end' in 'attributes', which is of non-class type 'int'
  112 |                            attributes.begin(), attributes.end()},
      |                                                           ^~~
In file included from /usr/local/include/opentelemetry/trace/tracer.h:14,
                 from /usr/local/include/opentelemetry/trace/tracer_provider.h:8,
                 from /usr/local/include/opentelemetry/sdk/trace/tracer_provider_factory.h:10,
                 from /opt/programs/opentelemetry-c/src/opentelemetry_c.cpp:35:
/usr/local/include/opentelemetry/trace/span_startoptions.h: At global scope:
/usr/local/include/opentelemetry/trace/span_startoptions.h:36:10: error: 'variant' in namespace 'opentelemetry::v1::nostd' does not name a template type
   36 |   nostd::variant<SpanContext, opentelemetry::context::Context> parent = SpanContext::GetInvalid();
      |          ^~~~~~~
In file included from /usr/local/include/opentelemetry/trace/tracer_provider.h:8,
                 from /usr/local/include/opentelemetry/sdk/trace/tracer_provider_factory.h:10,
                 from /opt/programs/opentelemetry-c/src/opentelemetry_c.cpp:35:
/usr/local/include/opentelemetry/trace/tracer.h:40:52: error: 'opentelemetry::v1::nostd::string_view' has not been declared
   40 |   virtual nostd::shared_ptr<Span> StartSpan(nostd::string_view name,
      |                                                    ^~~~~~~~~~~
/usr/local/include/opentelemetry/trace/tracer.h:45:44: error: 'opentelemetry::v1::nostd::string_view' has not been declared
   45 |   nostd::shared_ptr<Span> StartSpan(nostd::string_view name,
      |                                            ^~~~~~~~~~~
/usr/local/include/opentelemetry/trace/tracer.h:53:44: error: 'opentelemetry::v1::nostd::string_view' has not been declared
   53 |   nostd::shared_ptr<Span> StartSpan(nostd::string_view name,
      |                                            ^~~~~~~~~~~
/usr/local/include/opentelemetry/trace/tracer.h:60:44: error: 'opentelemetry::v1::nostd::string_view' has not been declared
   60 |   nostd::shared_ptr<Span> StartSpan(nostd::string_view nam

**Comment by wy12148** [comment] 2023-09-01 08:53
There's a lot of warning messages and error messages,maybe dozens of pages

**Comment by marcalff** [comment] 2023-09-01 15:14
A few comments here:
* Please indicate which version of opentelemetry-cpp is used, this will help investigations
* `-DWITH_JAEGER=ON` : Jaeger has been removed, this setting is no longer used.
* `-DCMAKE_CXX_STANDRAT=14` : this will have no effect due to the typo, use `-DCMAKE_CXX_STANDARD=14` instead.

**Comment by wy12148** [comment] 2023-09-02 01:42
> A few comments here:
> 
> * Please indicate which version of opentelemetry-cpp is used, this will help investigations
> * `-DWITH_JAEGER=ON` : Jaeger has been removed, this setting is no longer used.
> * `-DCMAKE_CXX_STANDRAT=14` : this will have no effect due to the typo, use `-DCMAKE_CXX_STANDARD=14` instead.
> 
> If possible, please paste the content of `opentelemetry_c.cpp`.

The version is v1.11.0. and sorry, I typed the wrong word.I'll go recompile it.

**Comment by marcalff** [comment] 2023-09-20 21:30
Closing, can not reproduce.

If the problem still exists after fixing the makefiles, please provide more details.

**Closed by marcalff** 2023-09-20 21:30 UTC
Labels: bug, triage/needs-information
