### ISSUE TITLE
Conflict of absl library compiled by bazel

### ISSUE THREAD

**Issue by zengguofei** [open-telemetry/opentelemetry-cpp#1166] opened 2021-12-29 08:32 UTC
I use bazel to integrate opentelemetry-cpp, and there is already an absl library in my project; I try to use the macro definition "HAVE_ABSEIL", but it does not work, it is still connected to the absl library of opentelemery.

I had to change the bazel compilation inside opentelemetry-cpp; change the absl dependency to my local library. I hope this dependency can provide good guidelines for external libraries.

![image](https://user-images.githubusercontent.com/31093334/147642318-115943b5-c717-4088-baac-48e3b8ae6f4d.png)
![image](https://user-images.githubusercontent.com/31093334/147642364-6ec775a3-3fb3-4602-938e-239fd653ada3.png)

**Comment by owent** [comment] 2021-12-29 08:56
Simular with #1065 .

**Comment by lalitb** [comment] 2021-12-29 20:48
Duplicate of #1065
Let's continue to track this in another issue, and close this.

**Closed by lalitb** 2021-12-29 20:48 UTC
