### ISSUE TITLE
WITH_STL shouldn't try importing gsl::span if std::span is not available.

### ISSUE THREAD

**Issue by lalitb** [open-telemetry/opentelemetry-cpp#813] opened 2021-06-01 12:47 UTC
As discussed in #742:
If the `WITH_STL` cmake option is enabled, the build should be using std::span if available (for C++20), and fall back to `nostd::span` instead of `gsl::span` ( or perhaps fail the build). Use `gsl::span` only if developers explicitly specify the `WITH_GSL` build option.

**Comment by maxgolov** [comment] 2021-06-02 04:08
I already added a fix for that here:

https://github.com/open-telemetry/opentelemetry-cpp/blob/d6f5d32ea8539d978060229731a5ea7807ec18c7/api/include/opentelemetry/std/span.h#L30

Could you please take a look at my PR? #771

**Comment by maxgolov** [comment] 2021-06-02 04:25
I added my comments to #742 here - https://github.com/open-telemetry/opentelemetry-cpp/pull/742#issuecomment-852709685

**Comment by maxgolov** [comment] 2021-06-03 01:42
I'll assign to myself. I believe I have a fix. Feedback is welcomed, in case if we want to decouple `STDLIB` vs `GSL`. But it's been described in the document that we fallback to `gsl::span` for C++17 , because `std::span` is only available starting from C++20.

**Comment by maxgolov** [comment] 2021-06-04 19:50
I would like to test this on latest build. Although we enable the option by-default for `STDLIB` build - we turn it off in case if customer's build system does not have `gsl` header. So the issue is largely alleviated: that way we do not force the customers to use the header.

Perhaps we should've switched our `nostd::span` implementation to `gsl::span`. Min bar for `gsl::span`, however, is C++14. So switching to GSL may not work too well for `gcc-4.8.x` . Or at least - I have not personally tested if it'd work specifically with that super-old compiler that barely has sufficient `C++11` support. Need a bit more time to research that. If it works, then we could either include a snapshot of GSL span as part of our API headers; or require the inclusion of it in the customer projects using OpenTelemetry C++ SDK.

Main motivation of defaulting to GSL span rather than implementing our own `nostd::span` :
- GSL span is better tested.
- GSL span is endorsed by CppCoreGuidelines.
- GSL span is approved in various secure lifecycle development processes.
- less maintenance headache (we do not want to maintain our own mini-STL library in OpenTelemetry).

**Comment by lalitb** [comment] 2021-10-15 21:35
> The gsl::span implementation in gsl-lite support gcc-4.8.x. Should we use it as gsl for old compilers?

What's the current behavior? I thought if `gsl-lite` is installed, and HAVE_GSL is enabled, it api/sdk will pick up `gsl-lite`. If this is not so, we can add support for that.

**Comment by maxgolov** [comment] 2021-12-29 21:40
@owent @lalitb - could you please folks take over the ownership of this issue? My main focus is on another project domain at the moment, and my ability to contribute to OpenTelemetry is limited.

**Comment by lalitb** [comment] 2021-12-29 23:27
Thanks, @maxgolov, have unassigned you and added a help-wanted tag. I will take it over if no one picks it. The immediate need for this issue is to remove the reference of HAVE_GSL from the code, and then we can have a separate issue to introduce the WITH_GSL cmake flag.

**Comment by esigo** [comment] 2021-12-29 23:38
@lalitb I can take it over.

**Closed** 2022-01-25 03:14 UTC
Labels: bug, help wanted, build and test
