### ISSUE TITLE
Warning: Multiple assignment operators specified for SpinLockMutex

### ISSUE THREAD

**Issue by SaiHarshaK** [open-telemetry/opentelemetry-cpp#2500] opened 2024-01-22 14:11 UTC
**Describe your environment** Describe any aspect of your environment relevant to the problem, including your platform, build system, version numbers of installed dependencies, etc. If you're reporting a problem with a specific version of a library in this repo, please check whether the problem has been fixed on main branch.

Issue exists in the main branch too, when building we see this warning pop up on using otlp metrics related code;
```
17>c:\work\ic3\d_nsshe_lcsminedgetmp\en-us\amd64chk\packages\opentelemetry.cpp.geneva.1.0.2300\api\include\opentelemetry\common\spin_lock_mutex.h(132) : error C4522: 'opentelemetry::v1::common::SpinLockMutex': multiple assignment operators specified
```

**Steps to reproduce**
Describe exactly how to reproduce the error. Include a code sample if applicable.
Build with this sample code:
```
#include "opentelemetry/exporters/etw/etw_tracer_exporter.h"
#include "opentelemetry/exporters/otlp/otlp_grpc_metric_exporter_factory.h"
#include "opentelemetry/metrics/provider.h"
#include "opentelemetry/sdk/metrics/export/periodic_exporting_metric_reader.h"
#include "opentelemetry/sdk/metrics/meter.h"
#include "opentelemetry/sdk/metrics/meter_provider.h"

using namespace OPENTELEMETRY_NAMESPACE;
using namespace opentelemetry::exporter::etw;
namespace otlp_exporter = opentelemetry::exporter::otlp;
namespace metrics_sdk = opentelemetry::sdk::metrics;
namespace metrics_api = opentelemetry::metrics;
namespace resource_ns = opentelemetry::sdk::resource;

    void InitOTelMetrics() 
    {
        // Initialize exporter
        otlp_exporter::OtlpGrpcMetricExporterOptions options;
        options.aggregation_temporality = static_cast<opentelemetry::v1::exporter::otlp::PreferredAggregationTemporality>(opentelemetry::v1::sdk::metrics::AggregationTemporality::kDelta);
        options.endpoint = "http://localhost:4317";
        auto exporter = otlp_exporter::OtlpGrpcMetricExporterFactory::Create(options);

        // Initialize metric reader
        metrics_sdk::PeriodicExportingMetricReaderOptions reader_options;
        reader_options.export_interval_millis = std::chrono::milliseconds(60 * 1000); // 1 min
        reader_options.export_timeout_millis  = std::chrono::milliseconds(500);
        std::unique_ptr<metrics_sdk::MetricReader> reader{
            new metrics_sdk::PeriodicExportingMetricReader(std::move(exporter), reader_options)};

        // Initialize MeterProvider
        resource_ns::ResourceAttributes attributes = {
            {"service", ServiceName}, {"_microsoft_metrics_account", "account"}, {"_microsoft_metrics_namespace", "counter"}
        };
        auto resource = resource_ns::Resource::Create(attributes);
        auto views = std::unique_ptr<metrics_sdk::ViewRegistry>(new metrics_sdk::ViewRegistry());
        auto provider = std::shared_ptr<metrics_api::MeterProvider>(new metrics_sdk::MeterProvider(std::move(views), resource));
        auto p = std::static_pointer_cast<metrics_sdk::MeterProvider>(provider);
        p->AddMetricReader(std::move(reader));
        metrics_api::Provider::SetMeterProvider(provider);
    }
```

**What is the expected behavior?**
No such warning is thrown

**What is the actual behavior?**
Warning C4522 is thrown.

**Additional context**

**Comment by marcalff** [comment] 2024-01-22 16:09
There are indeed two assignment operators in the code:

```
  SpinLockMutex &operator=(const SpinLockMutex &) = delete;
  SpinLockMutex &operator=(const SpinLockMutex &) volatile = delete;
```

What is surprising is that both are present since 2020-10-12, which is not recent, and this somehow builds.

The fix is to remove the volatile version.

@SaiHarshaK Could you confirm if the issue is resolved by removing the second line ?

Thanks.

**Comment by lalitb** [comment] 2024-01-22 16:46
Which MSVC compiler version, as this seems to be a false warning for perfectly legal code? However, we may also discuss whether we really need a `volatile` specifier for the synchronization mechanism.

**Comment by SaiHarshaK** [comment] 2024-01-22 16:58
Raised a PR if that helps. 

Adding version info here.
```
C:\Work\IC3\nsshe\minedgetmp>cl
Microsoft (R) C/C++ Optimizing Compiler Version 19.15.26726 for x64
```

**Closed** 2024-01-23 17:08 UTC
Labels: bug, needs-triage
