### ISSUE TITLE
otlp_http.lib not built

### ISSUE THREAD

**Issue by mititelud** [open-telemetry/opentelemetry-cpp#1566] opened 2022-08-15 15:15 UTC
### Discussed in https://github.com/open-telemetry/opentelemetry-cpp/discussions/1565

<div type='discussions-op-text'>

<sup>Originally posted by **mititelud** August 15, 2022</sup>
Hello,

I've been trying to build the otlp_http library in order to run the example_otlp_http example.
I've set up the dependecies needed and followed the opentelemetry build steps presented in repo_path/Install.md ### Building as standalone CMake Project
after i get to repo_path/build and run
cmake -DWITH_OTLP=ON -DWITH_OTLP_HTTP=ON ..  
or 
cmake ..
-- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.19044.
-- Building for architecture ARCH=x64
-- Found RE2 via CMake.
-- Could NOT find CURL (missing: CURL_LIBRARY) (found version "7.84.0")
-- PROTOBUF_PROTOC_EXECUTABLE=C:/work/vcpkg/installed/x64-windows/tools/protobuf/protoc.exe
-- gRPC_CPP_PLUGIN_EXECUTABLE=C:/work/vcpkg/installed/x64-windows/tools/grpc/grpc_cpp_plugin.exe
Using external nlohmann::json
GTEST_INCLUDE_DIRS   =
GTEST_BOTH_LIBRARIES = GTest::gtest;GTest::gtest_main
Building with nostd types...
-- Could NOT find CURL (missing: CURL_LIBRARY) (found version "7.84.0")
-- Could NOT find CURL (missing: CURL_LIBRARY) (found version "7.84.0")
PATH:C:/work/opentelemetry-cpp/examples/grpc/protos:C:/work/opentelemetry-cpp/examples/grpc/protos/messages.proto
-- Could NOT find CURL (missing: CURL_LIBRARY) (found version "7.84.0")
CMake Warning at examples/http/CMakeLists.txt:4 (message):
  Skipping http client/server example build: CURL not found

-- Configuring done
-- Generating done
-- Build files have been written to: C:/work/opentelemetry-cpp/build

I try to run the next step either with
cmake --build . --target install
or 
cmake --build . --target all_build
but the otlp_http library does not get built, while others are getting built (debug/opentelemetry_protol.lib, ... , examples/..../example_plugin.lib, exporters/...../opentelemetry_exporter_otlp_grpc, ... , sdk/..../opentelemetry_metrics.lib , sdk/..../opentelemetry_version.lib ).

Please help.

Thank you</div>

**Comment by owent** [comment] 2022-08-16 02:55
I think the season is curl development package is missing. curl executable is not enough.

> Just installing `curl` package is not enough, different package manager has different name, for example , you can install the development by `sudo apt install libcurl4-openssl-dev` on Ubuntu or Debian, `yum install libcurl-devel` on Rocky Linux , AlmaLinux, CentOS or RetHat, `pacman -S libcurl-devel` on Msys2 ant etc.
> Or you can also compile curl yourself and set `-DCURL_ROOT=<where the curl library in installed>` or `-DCMAKE_PREFIX_PATH=<where the curl library in installed>` when running cmake.

**Comment by lalitb** [comment] 2022-08-23 01:59
@mititelud  - Just wondering if you succeed in building the library?

**Comment by lalitb** [comment] 2022-08-29 20:21
Closing this. Please reopen if the issue is still there.

**Closed by lalitb** 2022-08-29 20:21 UTC

**Comment by bobsira** [comment] 2022-11-19 23:33
I am facing this issue as well when trying to set up OpenTel from my windows machine. Was there any solution to this?
