### ISSUE TITLE
opentelemetry-cpp 1.8.3 build failure

### ISSUE THREAD

**Issue by chenrui333** [open-telemetry/opentelemetry-cpp#2038] opened 2023-03-09 19:16 UTC
👋 trying to build the latest release, but run into some build issue. The error log is as below:

<details>
<summary>error build log</summary>

```
/tmp/opentelemetry-cpp-20230307-2861-1rrh1cf/opentelemetry-cpp-1.8.3/exporters/jaeger/src/TUDPTransport.cc:71:7: error: no type named 'close' in the global namespace
    ::THRIFT_CLOSESOCKET(socket_);
    ~~^
/opt/homebrew/include/thrift/transport/PlatformSocket.h:102:30: note: expanded from macro 'THRIFT_CLOSESOCKET'
#  define THRIFT_CLOSESOCKET close
                             ^
```

</details>

full build log, https://github.com/Homebrew/homebrew-core/actions/runs/4361014430/jobs/7624558826
relates to Homebrew/homebrew-core#125073

**Comment by lalitb** [comment] 2023-03-10 09:11
@chenrui333 - Looks like the thrift library version has got upgraded in homebrew, and it is messing up with the Jaeger exporter build for opentelemetry-cpp. The thrift version used by the opentelemetry-cpp CI pipeline is [0.14.1](https://github.com/open-telemetry/opentelemetry-cpp/blob/504644380a9482258604ad644531c643937b216c/third_party_release#L17), while the version present in homebrew is [0.18.1](https://formulae.brew.sh/formula/thrift).

Also, the Jaeger exporter has been [deprecated](https://github.com/open-telemetry/opentelemetry-cpp/blob/main/DEPRECATED.md#opentelemetry-cpp-exporter) in opentelemetry-cpp, and no new changes (including supporting the latest version of dependencies) would be entertained. The fix would be switch off the Jaeger exporter build from the opentelemetry-cpp by setting 
`                    "-DWITH_JAEGER=OFF",`

here - 
https://github.com/Homebrew/homebrew-core/blob/2e189b802bfacfadfc227fd7ce6f3d4748b54452/Formula/opentelemetry-cpp.rb#L35

The Jaeger exporter would be eventually removed from the opentelemetry-cpp, and there is already a active PR for it - https://github.com/open-telemetry/opentelemetry-cpp/pull/2031

**Comment by chenrui333** [comment] 2023-03-11 22:55
> Also, the Jaeger exporter has been [deprecated](https://github.com/open-telemetry/opentelemetry-cpp/blob/main/DEPRECATED.md#opentelemetry-cpp-exporter) in opentelemetry-cpp, and no new changes (including supporting the latest version of dependencies) would be entertained. The fix would be switch off the Jaeger exporter build from the opentelemetry-cpp by setting
> ` "-DWITH_JAEGER=OFF",`

thanks for the pointer, gonna try it now. 👍

**Comment by chenrui333** [comment] 2023-03-11 23:18
Also the absel used by the project is outdated as well and needs to update the min c++ version to c++14 (per abseil support policy)

**Comment by lalitb** [comment] 2023-03-12 04:03
> Also the absel used by the project is outdated as well and needs to update the min c++ version to c++14 (per abseil support policy)

Yes, it is planned for #1830

**Comment by valliscooper** [comment] 2023-03-15 08:03
I also ran into a build issue when trying to move to 1.8.3: 

opentelemetry-cpp/exporters/otlp/src/otlp_recordable_utils.cc: In static member function ‘static void opentelemetry::v1::exporter::otlp::OtlpRecordableUtils::PopulateRequest(opentelemetry::v1::nostd::span<std::unique_ptr<opentelemetry::v1::sdk::logs::Recordable> >&, opentelemetry::proto::collector::logs::v1::ExportLogsServiceRequest*)’:
3pp/opentelemetry-cpp/exporters/otlp/src/otlp_recordable_utils.cc:129:32: error: ‘class opentelemetry::proto::common::v1::InstrumentationScope’ has no member named ‘add_attributes’
  129 |                   proto_scope->add_attributes(), scope_attribute.first, scope_attribute.second);

cmake configured with WITH_LOGS_PREVIEW, WITH_METRICS_EXEMPLAR_PREVIEW and WITH_OTLP WITH_OTLP_GRPC because that's what I'm using currently.

**Comment by lalitb** [comment] 2023-03-15 15:03
> I also ran into a build issue when trying to move to 1.8.3:

Can you check if you are using the latest version of otel-proto (v0.19.0). This should be the latest if you are using it from otel-cpp submodule.

**Comment by valliscooper** [comment] 2023-03-17 06:46
> opentelemetry-cpp/exporters/otlp/src/otlp_recordable_utils.cc:

I've updated the sub-modules and that seems to have fixed it. thanks a lot for the tip.

**Comment by marcalff** [comment] 2023-03-28 17:16
Closing as the issue is resolved.

**Closed by marcalff** 2023-03-28 17:16 UTC
