### ISSUE TITLE
opentelemetry_trace cmake build error with -DBUILD_TESTING=ON

### ISSUE THREAD

**Issue by hurdad** [open-telemetry/opentelemetry-cpp#488] opened 2020-12-24 06:13 UTC
**Describe your environment** 
CentOS 8 
opentelemetry-cpp master:7d786ed8c9d3fb88bb1dd0f95c261ad05d2a4f16

**Steps to reproduce**
cmake -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Release -DWITH_OTLP=ON -DWITH_PROMETHEUS=ON -DBUILD_TESTING=ON -DWITH_EXAMPLES=ON .. && make -j8
-- The C compiler identification is GNU 8.4.1
-- The CXX compiler identification is GNU 8.4.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found Protobuf: /usr/lib64/libprotobuf.so;-lpthread (found version "3.14.0") 
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.11") 
-- Found OpenSSL: /usr/lib64/libcrypto.so (found version "1.1.1g")  
-- Found c-ares: /usr/lib64/cmake/c-ares/c-ares-config.cmake (found version "1.15.0") 
-- Found RE2 via CMake.
PROTOBUF_PROTOC_EXECUTABLE=/usr/bin/protoc
-- Found GTest: /usr/lib64/libgtest.so  
GTEST_INCLUDE_DIRS   = /usr/include
GTEST_BOTH_LIBRARIES = /usr/lib64/libgtest.so;/usr/lib64/libgtest_main.so
Building with nostd types...
-- Found CURL: /usr/lib64/libcurl.so (found version "7.61.1")  
-- Configuring done
-- Generating done
...
...

Scanning dependencies of target opentelemetry_trace
[ 31%] Building CXX object sdk/src/trace/CMakeFiles/opentelemetry_trace.dir/tracer_provider.cc.o
/home/user/git/opentelemetry-cpp/sdk/src/trace/tracer_provider.cc:1:10: fatal error: opentelemetry/sdk/trace/tracer_provider.h: No such file or directory
 #include "opentelemetry/sdk/trace/tracer_provider.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

Seems to only happen when -DBUILD_TESTING=ON

**Comment by lalitb** [comment] 2020-12-24 07:38
Can't reproduce it. 
If you don't mind, can you run these steps and post output of last two commands (3 & 4):

1. cd build && cmake -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Release -DWITH_OTLP=ON -DWITH_PROMETHEUS=ON -DBUILD_TESTING=ON -DWITH_EXAMPLES=ON .. 
2. cd sdk/src/trace
3. make -p | grep "CXX_INCLUDES =" | uniq
This should be something like : 

> CXX_INCLUDES = -I/home/\<user\>/opentelemetry-cpp/build/generated/third_party/opentelemetry-proto -I/home/\<user\>/opentelemetry-cpp/api/include -I/home/<user>/opentelemetry-cpp/sdk/include -I/home/<user>/opentelemetry-cpp/sdk

4. ls /home/<user>/opentelemetry-cpp/sdk/include/opentelemetry/sdk/trace/

**Comment by hurdad** [comment] 2020-12-24 19:57
Sorry this was my bad. I had moved the files by accident.

Will you be adding install support for the libs? right now make install just installs headers

**Comment by hurdad** [comment] 2020-12-24 20:00
Also this test is failing for me

```
The following tests FAILED:
	131 - trace.FastRandomNumberGeneratorTest.GenerateUniqueNumbers (Failed)
```

**Comment by hurdad** [comment] 2020-12-24 20:02
also i think you have typo in README.md

```
ubuntu-18.04 ( Default GCC Compiler - 7.5.0 )
```

**Comment by lalitb** [comment] 2020-12-28 05:42
> ```
> 	131 - trace.FastRandomNumberGeneratorTest.GenerateUniqueNumbers (Failed)
> ```

Yes, we have noticed this failing sometimes in our CI env, not getting consistent repo. If this is failing consistently for you, please provide us with your env ( OS version, compiler ) details.

>also i think you have typo in README.md ubuntu18.04 is listed twice

It's listed twice but with different compiler versions.

> Will you be adding install support for the libs? right now make install just installs headers

Yes this needs to be done. Right now it only installs `opentelemetry-cpp-api` ( which is all headers ), and `opentelemetry-cpp-sdk` is to be supported. 

On different notes, we encourage any support in fixing bugs and documentation from community. : )

**Comment by lalitb** [comment] 2021-04-19 09:29
Closing
 - install support for sdk is supported now.
 - Test failure `trace.FastRandomNumberGeneratorTest.GenerateUniqueNumbers` is not reproducible. Can open separate test if it fails again.

**Closed by lalitb** 2021-04-19 09:29 UTC
Labels: bug
